export const KEYWORDS = {
  topLevel: [
    "after",
    "around",
    "association",
    "associationClass",
    "class",
    "distributable",
    "filter",
    "generate",
    "interface",
    "mixset",
    "namespace",
    "statemachine",
    "strictness",
    "trait",
    "use",
    "--redefine",
  ],
  classLevel: [
    "abstract",
    "active",
    "const",
    "depend",
    "distributable",
    "emit",
    "enum",
    "inner",
    "isA",
    "key",
    "model",
    "self",
    "singleton",
    "sorted",
    "static",
  ],
  attribute: [
    "attribute",
    "attr",
    "autounique",
    "defaulted",
    "false",
    "immutable",
    "internal",
    "lazy",
    "settable",
    "true",
    "unique",
  ],
  method: [
    "public",
    "protected",
    "private",
    "static",
    "abstract",
    "pre",
    "custom",
    "generated",
    "all",
    "around_proceed",
  ],
  statemachine: [
    "after",
    "afterEvery",
    "as",
    "do",
    "entry",
    "exit",
    "final",
    "Final",
    "pooled",
    "queued",
    "statemachine",
    "unspecified",
  ],
  constraints: ["and", "not", "or"],
  modelConstraints: [
    "attribute",
    "attr",
    "has",
    "model",
    "of",
    "subclass",
    "superclass",
  ],
  tracing: [
    "add",
    "cardinality",
    "for",
    "giving",
    "remove",
    "trace",
    "tracer",
    "until",
    "where",
  ],
  testing: [
    "assertAttribute",
    "assertEqual",
    "assertFalse",
    "assertMethod",
    "assertNull",
    "assertTrue",
    "generic",
    "prefix",
    "regex",
    "suffix",
    "test",
  ],
  misc: [
    "forced",
    "hops",
    "ignore",
    "include",
    "includeFilter",
    "off",
    "RMI",
    "sub",
    "super",
    "WS",
  ],
};

export const ALL_KEYWORDS = Array.from(new Set(Object.values(KEYWORDS).flat()));
